<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
/* @var $this Mage_Catalog_Block_Layer_State */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">

    <div class="block-subtitle <?php echo Mage::helper('mana_filters')->renderHtml($this->getParentBlock(), 'currently_shopping_by') ? '' : 'hidden' ?>">
        <div class="m-subtitle-actions">
            <div class="m-expand-collapse">
                <div class="btn-expand-collapse"></div>
            </div>
        </div>
        <span><?php echo $this->__('Currently Shopping by:') ?></span>
    </div>
    <ol>
        <?php
        $group_size = '';
        $group_color = '';
        $group_brand = '';
        $group_price = '';
        ?>
    <?php foreach ($_filters as $_filter): ?>
    <?php if ($_html = $this->getValueHtml($_filter)) : ?>
        <?php echo $_html ?>
    <?php else : ?>
            <?php
            //xu ly lai de show group cac fiter item
            if($this->__($_filter->getName()) == 'Size'){
                $group_size.= '<span>'.$this->escapeHtml($_filter->getLabel()).'</span> ';
                $group_size.= '<a href="'.$_filter->getRemoveUrl().'" title="'.$this->__('Remove This Item').'" class="btn-remove1">'.$this->__('&#120;').'</a>';
            }else if($this->__($_filter->getName()) == 'Color'){
                //check neu co hinh thi dung hinh lam bg cho
                $url_file = Mage::getBaseDir('media').'/wysiwyg/swatches/';
                $url_bg = Mage::getBaseUrl('media').'/wysiwyg/swatches/';
                $label = strtolower($_filter->getLabel()).'.png';
                $file = $url_file.$label;
                $style = '';
                if (is_file($file)) {
                    $style = 'style="background: url('.$url_bg.$label.')"';
                }
                $group_color.= '<span><i '.$style.'></i>'.$this->escapeHtml($_filter->getLabel()).'</span> ';
                $group_color.= '<a href="'.$_filter->getRemoveUrl().'" title="'.$this->__('Remove This Item').'" class="btn-remove1">'.$this->__('&#120;').'</a>';
            }else if($this->__($_filter->getName()) == 'Brands'){
                $group_brand.= '<span>'.$this->escapeHtml($_filter->getLabel()).'</span> ';
                $group_brand.= '<a href="'.$_filter->getRemoveUrl().'" title="'.$this->__('Remove This Item').'" class="btn-remove1">'.$this->__('&#120;').'</a>';
            }else if($this->__($_filter->getName()) == 'Price'){
                $group_price.= '<span>'.$this->escapeHtml($_filter->getLabel()).'</span> ';
                $group_price.= '<a href="'.$_filter->getRemoveUrl().'" title="'.$this->__('Remove This Item').'" class="btn-remove1">'.$this->__('&#120;').'</a>';
            }else{
            ?>
                <li>
                    <a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove1"><?php echo $this->__('&#120;') ?></a>
                    <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <?php echo $_filter->getMShowSelected() ? $this->__('not') : '' ?> <?php echo $this->escapeHtml($_filter->getLabel()) ?>
                </li>
            <?php
            }
            ?>
        <!---->
    <?php endif; ?>
    <?php endforeach; ?>
        <?php echo $group_size ? '<li id="current_size">'.'<label>Size: </label>'.$group_size .'</li>': ''?>
        <?php echo $group_color ? '<li id="current_color">'.'<label>Color: </label>'.$group_color .'</li>': ''?>
        <?php echo $group_brand ? '<li id="current_brands">'.'<label>Brands: </label>'.$group_brand .'</li>': ''?>
        <?php echo $group_price ? '<li id="current_price">'.'<label>Price: </label>'.$group_price .'</li>': ''?>
        <li class="last_clearall"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></li>
    </ol>
    <?php if (!Mage::helper('mana_core')->isMageVersionEqualOrGreater('1.7') && ($_parent = $this->getParentBlock()) /*&& $_parent->getShowInFilter() != 'above_products'*/) : ?>
    <!--<div class="actions"><a href="<?php /*echo $this->getClearUrl() */?>"><?php /*echo $this->__('Clear All') */?></a></div>-->
    <?php endif; ?>
</div>
<?php endif; ?>
