<?php
    $_list = $this->getChild('alsoviewed.list');
    if (!$_list) :
        return;
    endif;

    $_productCollection = $_list->getProductCollection();
    if (!$_productCollection->getSize()) :
        return;
    endif;

    $_title = $_list->getTitle();
    if (null === $_title) :
        $_title = $this->getTitle();
    endif;
?>
<div class="detail_product_block detail_product_block_1 full left">
    <div class="detail_product_block_title full left">
        <label>people who viewed also viewed</label>
    </div>
    <div class="box-collateral alsoviewed full left">
        <!--<h2><?php /*echo $this->__($_title); */?></h2>-->
        <?php echo $this->getChildHtml('alsoviewed.list') ?>
    </div>
</div><!-- end detail_product_block_1 -->
